local: &local
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true

production:
  adapter: redis
  url: redis://redistogo:37c0c9c0d1b9e13a9ecb5e964754f6e5@sculpin.redistogo.com:10840/

development: *local

test: *local
